language: node_js
node_js: stable

notifications:
   webhooks: https://oapi.dingtalk.com/robot/send?access_token=a0918ec1b0461056fb9953fe2b03ecc3074a629e88992f327cc94bae93349e9e

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

script:
  - yarn run build:travis

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

after_success:
  - ./deploy/qshell account $AK $SK liyang
  - ./deploy/qshell qupload ./deploy/upload.conf
  - ./deploy/qshell cdnrefresh --dirs -i ./deploy/cdnrefresh.txt